.TH "addsouvenir.cpp" 3 "Mon Mar 23 2020" "Version 1" "CS1D - Project1 - College Touring" \" -*- nroff -*-
.ad l
.nh
.SH NAME
addsouvenir.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'addsouvenir\&.h'\fP
.br
\fC#include 'ui_addsouvenir\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D - Project1 - College Touring from the source code\&.
