.TH "adminwindow.cpp" 3 "Mon Mar 23 2020" "Version 1" "CS1D - Project1 - College Touring" \" -*- nroff -*-
.ad l
.nh
.SH NAME
adminwindow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'adminwindow\&.h'\fP
.br
\fC#include 'ui_adminwindow\&.h'\fP
.br
\fC#include 'confirmpage\&.h'\fP
.br
\fC#include 'loginwindow\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D - Project1 - College Touring from the source code\&.
