.TH "AdminWindow" 3 "Mon May 11 2020" "Version 1" "CS1D - Project2 - Baseball" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdminWindow \- class initializes \fBAdminWindow\fP UI and manages all Admin only permissive execution in editing user database, college database, souv database, etc  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <adminwindow\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBupdateCombo\fP ()"
.br
.ti -1c
.RI "\fBAdminWindow\fP (QWidget *parent=nullptr)"
.br
.RI "explicit default Constructor "
.ti -1c
.RI "void \fBupdateCollegeTable\fP ()"
.br
.RI "updates sql data table for colleges when called "
.ti -1c
.RI "void \fBupdateSouvenirTable\fP ()"
.br
.RI "updates sql data table for college souvenirs when called "
.ti -1c
.RI "\fB~AdminWindow\fP ()"
.br
.RI "Destructor\&. "
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBonInitialise\fP ()"
.br
.RI "runs a verification of \fBconfirmPage\fP, if verfied, initalizes distance, college, souvenir lists, updates appropiate data tables and UI models "
.ti -1c
.RI "void \fBclearCollegeData\fP ()"
.br
.RI "clears database of data "
.ti -1c
.RI "void \fBon_addSouvenir_released\fP ()"
.br
.RI "executes \fBaddSouvenir\fP class obj "
.ti -1c
.RI "void \fBon_removeSouvenir_released\fP ()"
.br
.RI "deletes souvenir from data tables "
.ti -1c
.RI "void \fBonAddColleges\fP ()"
.br
.RI "adds college to connected database "
.ti -1c
.RI "void \fBon_souvenirView_clicked\fP (const QModelIndex &index)"
.br
.RI "displays and prints data from souvenir data set to UI "
.ti -1c
.RI "void \fBon_removeSouvenir_2_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_pushButton_5_released\fP ()"
.br
.ti -1c
.RI "void \fBon_pushButton_2_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_addMLB_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_searchButton_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_showALL_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_showStadiums_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_showStadiums_2_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_pushButton_3_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_pushButton_4_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_pushButton_6_clicked\fP ()"
.br
.ti -1c
.RI "void \fBsouvTable\fP ()"
.br
.ti -1c
.RI "void \fBon_pushButton_7_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_souTable_clicked\fP (const QModelIndex &index)"
.br
.ti -1c
.RI "void \fBon_pushButton_8_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_updateButton_clicked\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QString \fBsouve\fP"
.br
.RI "string stores temp souv data "
.ti -1c
.RI "Ui::AdminWindow * \fBui\fP"
.br
.RI "points to adminwindow UI "
.ti -1c
.RI "\fBDbManager\fP \fBmyDb\fP = \fBDbManager\fP(PROJECT_PATH + '/college\&.db')"
.br
.RI "assigns DB to predefined PROJECT_PATH constant "
.in -1c
.SH "Detailed Description"
.PP 
class initializes \fBAdminWindow\fP UI and manages all Admin only permissive execution in editing user database, college database, souv database, etc 

\fBAdminWindow\fP allows admin users only to intialize lists, edit lists, add individual college, souv data values 
.PP
Definition at line 27 of file adminwindow\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AdminWindow::AdminWindow (QWidget * parent = \fCnullptr\fP)\fC [explicit]\fP"

.PP
explicit default Constructor Constructor intializes UI for adminwindow calls \fBupdateCollegeTable()\fP and \fBupdateSouvenirTable()\fP 
.PP
\fBParameters\fP
.RS 4
\fI*parent\fP - for QDialog 
.RE
.PP

.PP
Definition at line 6 of file adminwindow\&.cpp\&.
.PP
References AdminWindow(), souvTable(), updateCollegeTable(), and updateSouvenirTable()\&.
.PP
Referenced by AdminWindow()\&.
.SS "AdminWindow::~AdminWindow ()"

.PP
Destructor\&. Close the \fBAdminWindow\fP UI 
.PP
Definition at line 17 of file adminwindow\&.cpp\&.
.PP
References ui\&.
.SH "Member Function Documentation"
.PP 
.SS "void AdminWindow::clearCollegeData ()\fC [private]\fP, \fC [slot]\fP"

.PP
clears database of data 
.PP
\fBReturns\fP
.RS 4
void - none 
.RE
.PP

.PP
Definition at line 95 of file adminwindow\&.cpp\&.
.PP
References confirmpage::getData(), confirmpage::on_okButton_released(), updateCollegeTable(), and updateSouvenirTable()\&.
.SS "void AdminWindow::on_addMLB_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 181 of file adminwindow\&.cpp\&.
.PP
References confirmpage::getData(), confirmpage::on_okButton_released(), updateCollegeTable(), and updateSouvenirTable()\&.
.SS "void AdminWindow::on_addSouvenir_released ()\fC [private]\fP, \fC [slot]\fP"

.PP
executes \fBaddSouvenir\fP class obj 
.PP
\fBReturns\fP
.RS 4
void - none 
.RE
.PP

.PP
Definition at line 118 of file adminwindow\&.cpp\&.
.PP
References addSouvenir::on_pushButton_2_released(), and updateSouvenirTable()\&.
.SS "void AdminWindow::on_pushButton_2_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 176 of file adminwindow\&.cpp\&.
.SS "void AdminWindow::on_pushButton_3_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 311 of file adminwindow\&.cpp\&.
.SS "void AdminWindow::on_pushButton_4_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 336 of file adminwindow\&.cpp\&.
.SS "void AdminWindow::on_pushButton_5_released ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 167 of file adminwindow\&.cpp\&.
.SS "void AdminWindow::on_pushButton_6_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 361 of file adminwindow\&.cpp\&.
.SS "void AdminWindow::on_pushButton_7_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 407 of file adminwindow\&.cpp\&.
.PP
References addSouvenir::on_pushButton_2_released(), and souvTable()\&.
.SS "void AdminWindow::on_pushButton_8_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 443 of file adminwindow\&.cpp\&.
.PP
References confirmpage::getData(), confirmpage::on_okButton_released(), and souvTable()\&.
.SS "void AdminWindow::on_removeSouvenir_2_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 162 of file adminwindow\&.cpp\&.
.SS "void AdminWindow::on_removeSouvenir_released ()\fC [private]\fP, \fC [slot]\fP"

.PP
deletes souvenir from data tables 
.PP
\fBReturns\fP
.RS 4
void - none 
.RE
.PP

.PP
Definition at line 128 of file adminwindow\&.cpp\&.
.SS "void AdminWindow::on_searchButton_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 224 of file adminwindow\&.cpp\&.
.SS "void AdminWindow::on_showALL_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 250 of file adminwindow\&.cpp\&.
.SS "void AdminWindow::on_showStadiums_2_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 291 of file adminwindow\&.cpp\&.
.SS "void AdminWindow::on_showStadiums_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 271 of file adminwindow\&.cpp\&.
.SS "void AdminWindow::on_souTable_clicked (const QModelIndex & index)\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 417 of file adminwindow\&.cpp\&.
.SS "void AdminWindow::on_souvenirView_clicked (const QModelIndex & index)\fC [private]\fP, \fC [slot]\fP"

.PP
displays and prints data from souvenir data set to UI 
.PP
\fBReturns\fP
.RS 4
void - none 
.RE
.PP

.PP
Definition at line 156 of file adminwindow\&.cpp\&.
.SS "void AdminWindow::on_updateButton_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 491 of file adminwindow\&.cpp\&.
.PP
References confirmpage::getData(), confirmpage::on_okButton_released(), and souvTable()\&.
.SS "void AdminWindow::onAddColleges ()\fC [private]\fP, \fC [slot]\fP"

.PP
adds college to connected database 
.PP
\fBReturns\fP
.RS 4
void - none 
.RE
.PP

.PP
Definition at line 133 of file adminwindow\&.cpp\&.
.PP
References confirmpage::getData(), confirmpage::on_okButton_released(), updateCollegeTable(), and updateSouvenirTable()\&.
.SS "void AdminWindow::onInitialise ()\fC [private]\fP, \fC [slot]\fP"

.PP
runs a verification of \fBconfirmPage\fP, if verfied, initalizes distance, college, souvenir lists, updates appropiate data tables and UI models 
.PP
\fBReturns\fP
.RS 4
void - none 
.RE
.PP

.PP
Definition at line 62 of file adminwindow\&.cpp\&.
.PP
References confirmpage::getData(), confirmpage::on_okButton_released(), updateCollegeTable(), and updateSouvenirTable()\&.
.SS "void AdminWindow::souvTable ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 385 of file adminwindow\&.cpp\&.
.PP
Referenced by AdminWindow(), on_pushButton_7_clicked(), on_pushButton_8_clicked(), and on_updateButton_clicked()\&.
.SS "void AdminWindow::updateCollegeTable ()"

.PP
updates sql data table for colleges when called 
.PP
\fBReturns\fP
.RS 4
void - none 
.RE
.PP

.PP
Definition at line 22 of file adminwindow\&.cpp\&.
.PP
Referenced by AdminWindow(), clearCollegeData(), on_addMLB_clicked(), onAddColleges(), and onInitialise()\&.
.SS "void AdminWindow::updateCombo ()"

.PP
Definition at line 204 of file adminwindow\&.cpp\&.
.SS "void AdminWindow::updateSouvenirTable ()"

.PP
updates sql data table for college souvenirs when called 
.PP
\fBReturns\fP
.RS 4
void - none 
.RE
.PP

.PP
Definition at line 41 of file adminwindow\&.cpp\&.
.PP
Referenced by AdminWindow(), clearCollegeData(), on_addMLB_clicked(), on_addSouvenir_released(), onAddColleges(), and onInitialise()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDbManager\fP AdminWindow::myDb = \fBDbManager\fP(PROJECT_PATH + '/college\&.db')\fC [private]\fP"

.PP
assigns DB to predefined PROJECT_PATH constant 
.PP
Definition at line 144 of file adminwindow\&.h\&.
.SS "QString AdminWindow::souve\fC [private]\fP"

.PP
string stores temp souv data 
.PP
Definition at line 134 of file adminwindow\&.h\&.
.SS "Ui::AdminWindow* AdminWindow::ui\fC [private]\fP"

.PP
points to adminwindow UI 
.PP
Definition at line 139 of file adminwindow\&.h\&.
.PP
Referenced by ~AdminWindow()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D - Project2 - Baseball from the source code\&.
