.TH "confirmpage.cpp" 3 "Mon May 11 2020" "Version 1" "CS1D - Project2 - Baseball" \" -*- nroff -*-
.ad l
.nh
.SH NAME
confirmpage.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'confirmpage\&.h'\fP
.br
\fC#include 'ui_confirmpage\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D - Project2 - Baseball from the source code\&.
