.TH "dbmanager.h" 3 "Mon Mar 23 2020" "Version 1" "CS1D - Project1 - College Touring" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbmanager.h
.SH SYNOPSIS
.br
.PP
\fC#include <QAbstractItemModel>\fP
.br
\fC#include <QtSql>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QFileInfo>\fP
.br
\fC#include 'QSqlDatabase'\fP
.br
\fC#include 'QSqlQuery'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDbManager\fP"
.br
.RI "SQL Database Manager class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D - Project1 - College Touring from the source code\&.
