.TH "loginWindow" 3 "Mon Mar 23 2020" "Version 1" "CS1D - Project1 - College Touring" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loginWindow \- class sets ui and manages execution for validating username and password  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <loginwindow\&.h>\fP
.SH "Detailed Description"
.PP 
class sets ui and manages execution for validating username and password 

\fBloginWindow\fP validates the credentials entered by the user, conncects to the database, and prompts the appropiate screen for the appropate user to execute after the user has been logged in and validated 

.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D - Project1 - College Touring from the source code\&.
