.TH "loginwindow.h" 3 "Mon Mar 23 2020" "Version 1" "CS1D - Project1 - College Touring" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loginwindow.h
.SH SYNOPSIS
.br
.PP
\fC#include <QMainWindow>\fP
.br
\fC#include 'dbmanager\&.h'\fP
.br
\fC#include 'adminwindow\&.h'\fP
.br
\fC#include 'tripplanner\&.h'\fP
.br
\fC#include <QPixmap>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLoginWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D - Project1 - College Touring from the source code\&.
