.TH "tripplanner.cpp" 3 "Mon May 11 2020" "Version 1" "CS1D - Project2 - Baseball" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tripplanner.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'tripplanner\&.h'\fP
.br
\fC#include 'ui_tripplanner\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'QVBoxLayout'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D - Project2 - Baseball from the source code\&.
