.TH "tripplanner.h" 3 "Mon May 11 2020" "Version 1" "CS1D - Project2 - Baseball" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tripplanner.h
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include <QList>\fP
.br
\fC#include 'graphinfo\&.h'\fP
.br
\fC#include 'dbmanager\&.h'\fP
.br
\fC#include <qcheckbox\&.h>\fP
.br
\fC#include 'tripsummary\&.h'\fP
.br
\fC#include 'tripprogress\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtripPlanner\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D - Project2 - Baseball from the source code\&.
