.TH "tripprogress.h" 3 "Mon May 11 2020" "Version 1" "CS1D - Project2 - Baseball" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tripprogress.h
.SH SYNOPSIS
.br
.PP
\fC#include <QMainWindow>\fP
.br
\fC#include 'dbmanager\&.h'\fP
.br
\fC#include 'confirmpage\&.h'\fP
.br
\fC#include 'tripsummary\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtripprogress\fP"
.br
.RI "class for displaying and calculating student trip progress, destinations, and student shopping cart for souverniers "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CS1D - Project2 - Baseball from the source code\&.
