CS1D - Project1 - College Touring: confirmpage Class Reference
confirmpage Class Reference
#include <confirmpage.h>
Public Member Functions
confirmpage (QWidget *parent=nullptr)
explicit default Constructor
~confirmpage ()
Destructor.
confirmpage (QWidget *parent, bool &returnAnswer)
bool getData ()
returns answer to calling function
Private Slots
void on_okButton_released ()
sets answer to true, hides ui
void on_cancelButton_released ()
sets answer to false, hides ui
Private Attributes
Ui::confirmpage * ui
points to confirmpage UI
bool answer = false
declares boolean to default val
Detailed Description
Definition at line 24 of file confirmpage.h.
Constructor & Destructor Documentation
confirmpage() [1/2]
confirmpage::confirmpage (QWidget * parent = nullptr) explicit
explicit default Constructor
Constructor intializes UI for confirmpage
Parameters
*parent - for QDialog
Definition at line 4 of file confirmpage.cpp.
~confirmpage()
confirmpage::~confirmpage ()
Destructor.
Close the loginwindow UI
Definition at line 11 of file confirmpage.cpp.
References ui.
confirmpage() [2/2]
confirmpage::confirmpage (QWidget * parent, bool & returnAnswer)
Member Function Documentation
getData()
bool confirmpage::getData ()
returns answer to calling function
Returns
bool- answer
Definition at line 16 of file confirmpage.cpp.
References answer.
Referenced by AdminWindow::clearCollegeData(), tripprogress::nextTrip(), tripprogress::on_pushButton_4_released(), addSouvenir::on_pushButton_released(), AdminWindow::on_removeSouvenir_2_clicked(), AdminWindow::on_removeSouvenir_released(), AdminWindow::onAddColleges(), and AdminWindow::onInitialise().
on_cancelButton_released
void confirmpage::on_cancelButton_released () private slot
sets answer to false, hides ui
Returns
void- none
Definition at line 28 of file confirmpage.cpp.
References answer.
on_okButton_released
void confirmpage::on_okButton_released () private slot
sets answer to true, hides ui
Returns
void- none
Definition at line 22 of file confirmpage.cpp.
References answer.
Referenced by AdminWindow::clearCollegeData(), tripprogress::nextTrip(), tripprogress::on_pushButton_4_released(), addSouvenir::on_pushButton_released(), AdminWindow::on_removeSouvenir_2_clicked(), AdminWindow::on_removeSouvenir_released(), AdminWindow::onAddColleges(), and AdminWindow::onInitialise().
Member Data Documentation
answer
bool confirmpage::answer = false private
declares boolean to default val
Definition at line 72 of file confirmpage.h.
Referenced by getData(), on_cancelButton_released(), and on_okButton_released().
ui
Ui::confirmpage* confirmpage::ui private
points to confirmpage UI
Definition at line 67 of file confirmpage.h.
Referenced by ~confirmpage().
The documentation for this class was generated from the following files:
confirmpage.h
confirmpage.cpp