CS1D - Project2 - Baseball: tripPlanner Class Reference
tripPlanner Class Reference
#include <tripplanner.h>
Public Slots
void onTypologyClick ()
Displays stadiums by ballpark topology in MLB information tab.
void onAmericanClick ()
Displays stadiums in the American League in MLB information tab.
void onShowClick ()
Displays all stadiums in MLB information tab.
void onNationalClick ()
Displays stadiums in the National League in MLB information tab.
void onStadiumsClick ()
Displays teams and stadiums sorted by stadium name in MLB information tab.
void onTeamClick ()
Displays teams and stadiums sorted by team name in MLB information tab.
void onSearchClick ()
Displays team that matches searched team name in MLB information tab.
void onRoofClick ()
Displays stadiums by roof type in MLB information tab.
void onDateClick ()
Displays stadiums by creation year in MLB information tab.
void onSeatingClick ()
Displays stadiums by number of seats in MLB information tab.
void onGreatClick ()
Displays stadiums by largest distance field in MLB information tab.
void onLeastClick ()
Displays stadiums by shortest distance field in MLB information tab.
void initializeList ()
Initalizes checkbox list.
void onPlanClick ()
Plans trip path requires a valid tripID entered uses the algorithm function to determine path through stadiums requires a valid starting stadium.
void onGraphInfoClick ()
Opens a dialogue displaying the BFS, DFS, and MST distances of the stadium graph.
void onStartTrip ()
Initiates the start of the trip requires valid trip plan and ID.
Public Member Functions
tripPlanner (QWidget *parent=nullptr)
default explicit Constructor
~tripPlanner ()
Destructor.
void updateCombo ()
Updates combo box in MLB information.
void updateDistTable ()
Updates the table in the Distances tab.
void updateMLBTable ()
Updates the table in the MLB information tab.
void selectedCollegeList ()
Creates the checkbox list of stadiums.
bool collegeDoesExist (QString colName)
Checks if a stadium name exists.
bool planDoesExist (QString colName)
Checks if the given trip ID already exists.
void showTrip (QString ID)
Displays the trip order of the stadiums.
void updateComboTwo ()
Updates teh combo box for available stadiums.
void algorithm ()
Trip planning algorithm using dijkstra.
Private Slots
void ChecboxChanged ()
Private Attributes
Ui::tripPlanner * ui
points to tripPlanner UI
DbManager myDb = DbManager(PROJECT_PATH + "/college.db")
assigns DB to predefined PROJECT_PATH constant
tripprogress * progress
QVector< QCheckBox * > checkBoxVector
QStringList selectedColleges
QStringList plannedColleges
int distance
QString id
QList< int > distanceTo
graphInfo * info
vector< QString > path
vector< QString > remainingChoices
vector< int > distNext
Detailed Description
Definition at line 16 of file tripplanner.h.
Constructor & Destructor Documentation
tripPlanner()
tripPlanner::tripPlanner (QWidget * parent = nullptr) explicit
default explicit Constructor
Constructor sets up ui for tripPlanner and executes initalizeList(), and updateCombo()
Parameters
*parent - for QDialog
Definition at line 7 of file tripplanner.cpp.
References initializeList(), updateCombo(), updateComboTwo(), updateDistTable(), and updateMLBTable().
~tripPlanner()
tripPlanner::~tripPlanner ()
Destructor.
Close the tripPlanner UI
Definition at line 21 of file tripplanner.cpp.
References ui.
Member Function Documentation
algorithm()
void tripPlanner::algorithm ()
Trip planning algorithm using dijkstra.
Definition at line 627 of file tripplanner.cpp.
References algorithm().
Referenced by algorithm(), and onPlanClick().
ChecboxChanged
void tripPlanner::ChecboxChanged () private slot
Definition at line 406 of file tripplanner.cpp.
collegeDoesExist()
bool tripPlanner::collegeDoesExist (QString colName)
Checks if a stadium name exists.
Definition at line 547 of file tripplanner.cpp.
initializeList
void tripPlanner::initializeList () slot
Initalizes checkbox list.
Definition at line 367 of file tripplanner.cpp.
Referenced by tripPlanner().
onAmericanClick
void tripPlanner::onAmericanClick () slot
Displays stadiums in the American League in MLB information tab.
Definition at line 51 of file tripplanner.cpp.
onDateClick
void tripPlanner::onDateClick () slot
Displays stadiums by creation year in MLB information tab.
Definition at line 277 of file tripplanner.cpp.
onGraphInfoClick
void tripPlanner::onGraphInfoClick () slot
Opens a dialogue displaying the BFS, DFS, and MST distances of the stadium graph.
Definition at line 618 of file tripplanner.cpp.
References info, and graphInfo::onCloseClick().
onGreatClick
void tripPlanner::onGreatClick () slot
Displays stadiums by largest distance field in MLB information tab.
Definition at line 321 of file tripplanner.cpp.
onLeastClick
void tripPlanner::onLeastClick () slot
Displays stadiums by shortest distance field in MLB information tab.
Definition at line 344 of file tripplanner.cpp.
onNationalClick
void tripPlanner::onNationalClick () slot
Displays stadiums in the National League in MLB information tab.
Definition at line 98 of file tripplanner.cpp.
onPlanClick
void tripPlanner::onPlanClick () slot
Plans trip path requires a valid tripID entered uses the algorithm function to determine path through stadiums requires a valid starting stadium.
Definition at line 472 of file tripplanner.cpp.
References algorithm(), distance, and selectedCollegeList().
onRoofClick
void tripPlanner::onRoofClick () slot
Displays stadiums by roof type in MLB information tab.
Definition at line 254 of file tripplanner.cpp.
onSearchClick
void tripPlanner::onSearchClick () slot
Displays team that matches searched team name in MLB information tab.
Definition at line 227 of file tripplanner.cpp.
onSeatingClick
void tripPlanner::onSeatingClick () slot
Displays stadiums by number of seats in MLB information tab.
Definition at line 298 of file tripplanner.cpp.
onShowClick
void tripPlanner::onShowClick () slot
Displays all stadiums in MLB information tab.
Definition at line 76 of file tripplanner.cpp.
onStadiumsClick
void tripPlanner::onStadiumsClick () slot
Displays teams and stadiums sorted by stadium name in MLB information tab.
Definition at line 124 of file tripplanner.cpp.
onStartTrip
void tripPlanner::onStartTrip () slot
Initiates the start of the trip requires valid trip plan and ID.
Definition at line 666 of file tripplanner.cpp.
onTeamClick
void tripPlanner::onTeamClick () slot
Displays teams and stadiums sorted by team name in MLB information tab.
Definition at line 145 of file tripplanner.cpp.
onTypologyClick
void tripPlanner::onTypologyClick () slot
Displays stadiums by ballpark topology in MLB information tab.
Definition at line 26 of file tripplanner.cpp.
planDoesExist()
bool tripPlanner::planDoesExist (QString colName)
Checks if the given trip ID already exists.
Definition at line 561 of file tripplanner.cpp.
selectedCollegeList()
void tripPlanner::selectedCollegeList ()
Creates the checkbox list of stadiums.
Definition at line 442 of file tripplanner.cpp.
Referenced by onPlanClick().
showTrip()
void tripPlanner::showTrip (QString ID)
Displays the trip order of the stadiums.
Definition at line 574 of file tripplanner.cpp.
updateCombo()
void tripPlanner::updateCombo ()
Updates combo box in MLB information.
Definition at line 166 of file tripplanner.cpp.
Referenced by tripPlanner().
updateComboTwo()
void tripPlanner::updateComboTwo ()
Updates teh combo box for available stadiums.
Definition at line 598 of file tripplanner.cpp.
Referenced by tripPlanner().
updateDistTable()
void tripPlanner::updateDistTable ()
Updates the table in the Distances tab.
Definition at line 187 of file tripplanner.cpp.
Referenced by tripPlanner().
updateMLBTable()
void tripPlanner::updateMLBTable ()
Updates the table in the MLB information tab.
Definition at line 206 of file tripplanner.cpp.
Referenced by tripPlanner().
Member Data Documentation
checkBoxVector
QVector<QCheckBox*> tripPlanner::checkBoxVector private
Definition at line 203 of file tripplanner.h.
distance
int tripPlanner::distance private
Definition at line 208 of file tripplanner.h.
Referenced by onPlanClick().
distanceTo
QList<int> tripPlanner::distanceTo private
Definition at line 212 of file tripplanner.h.
distNext
vector<int> tripPlanner::distNext private
Definition at line 220 of file tripplanner.h.
id
QString tripPlanner::id private
Definition at line 210 of file tripplanner.h.
info
graphInfo* tripPlanner::info private
Definition at line 214 of file tripplanner.h.
Referenced by onGraphInfoClick().
myDb
DbManager tripPlanner::myDb = DbManager(PROJECT_PATH + "/college.db") private
assigns DB to predefined PROJECT_PATH constant
Definition at line 199 of file tripplanner.h.
path
vector<QString> tripPlanner::path private
Definition at line 216 of file tripplanner.h.
plannedColleges
QStringList tripPlanner::plannedColleges private
Definition at line 207 of file tripplanner.h.
progress
tripprogress* tripPlanner::progress private
Definition at line 201 of file tripplanner.h.
remainingChoices
vector<QString> tripPlanner::remainingChoices private
Definition at line 218 of file tripplanner.h.
selectedColleges
QStringList tripPlanner::selectedColleges private
Definition at line 205 of file tripplanner.h.
ui
Ui::tripPlanner* tripPlanner::ui private
points to tripPlanner UI
Definition at line 193 of file tripplanner.h.
Referenced by ~tripPlanner().
The documentation for this class was generated from the following files:
tripplanner.h
tripplanner.cpp