CS1D - Project1 - College Touring: tripSummary Class Reference
tripSummary Class Reference
class for generating and updating sql data from read DB and overall planned trip summary
#include <tripsummary.h>
Public Member Functions
tripSummary (QWidget *parent=nullptr)
default explicit Constructor
tripSummary (const QString &id, QWidget *parent=nullptr)
explicit Constructor
~tripSummary ()
Destructor.
Private Slots
void on_school_comboBox_currentIndexChanged (const QString &arg1)
prepares a query and binds tripId and collegeNames to appropiate Database
void updateTripSchoolList ()
updates tripID and UI model when called. Prepares query for all availble tripIDs
void updateSchoolComboBox ()
void updateTotalDistance ()
void updateSchoolTotal ()
void updateTripTotal ()
Private Attributes
Ui::tripSummary * ui
points to tripSummary UI
DbManager myDb = DbManager(PROJECT_PATH + "/college.db")
assigns DB to predefined PROJECT_PATH constant
QString tripID
Detailed Description
class for generating and updating sql data from read DB and overall planned trip summary
tripSummary displays an overview of what the user has planned for his trip this updates all data from souvenier, collegename, price, quantity, etc for the plan tripped
Definition at line 26 of file tripsummary.h.
Constructor & Destructor Documentation
tripSummary() [1/2]
tripSummary::tripSummary (QWidget * parent = nullptr) explicit
default explicit Constructor
Constructor sets up ui for tripSummary
Parameters
*parent - for QDialog
Definition at line 4 of file tripsummary.cpp.
tripSummary() [2/2]
tripSummary::tripSummary (const QString & id, QWidget * parent = nullptr) explicit
explicit Constructor
Constructor sets up ui for tripSummary and initilalizes tripId
Parameters
*parent - for QDialog
id - tripID
Definition at line 11 of file tripsummary.cpp.
References tripSummary(), updateSchoolComboBox(), updateTotalDistance(), updateTripSchoolList(), and updateTripTotal().
Referenced by tripSummary().
~tripSummary()
tripSummary::~tripSummary ()
Destructor.
Close the tripSummary UI
Definition at line 24 of file tripsummary.cpp.
References ui.
Member Function Documentation
on_school_comboBox_currentIndexChanged
void tripSummary::on_school_comboBox_currentIndexChanged (const QString & arg1) private slot
prepares a query and binds tripId and collegeNames to appropiate Database
Returns
nothing - void
Definition at line 31 of file tripsummary.cpp.
References updateSchoolTotal().
Referenced by tripprogress::nextTrip().
updateSchoolComboBox
void tripSummary::updateSchoolComboBox () private slot
Definition at line 83 of file tripsummary.cpp.
Referenced by tripSummary().
updateSchoolTotal
void tripSummary::updateSchoolTotal () private slot
Definition at line 128 of file tripsummary.cpp.
Referenced by on_school_comboBox_currentIndexChanged().
updateTotalDistance
void tripSummary::updateTotalDistance () private slot
Definition at line 104 of file tripsummary.cpp.
Referenced by tripSummary().
updateTripSchoolList
void tripSummary::updateTripSchoolList () private slot
updates tripID and UI model when called. Prepares query for all availble tripIDs
Returns
nothing - void
Definition at line 61 of file tripsummary.cpp.
Referenced by tripSummary().
updateTripTotal
void tripSummary::updateTripTotal () private slot
Definition at line 153 of file tripsummary.cpp.
Referenced by tripSummary().
Member Data Documentation
myDb
DbManager tripSummary::myDb = DbManager(PROJECT_PATH + "/college.db") private
assigns DB to predefined PROJECT_PATH constant
Definition at line 88 of file tripsummary.h.
tripID
QString tripSummary::tripID private
Definition at line 90 of file tripsummary.h.
ui
Ui::tripSummary* tripSummary::ui private
points to tripSummary UI
Definition at line 83 of file tripsummary.h.
Referenced by ~tripSummary().
The documentation for this class was generated from the following files:
tripsummary.h
tripsummary.cpp