CS1D - Project1 - College Touring: tripprogress Class Reference
tripprogress Class Reference
class for displaying and calculating student trip progress, destinations, and student shopping cart for souverniers
#include <tripprogress.h>
Public Slots
void onLoadClick ()
initializes tripProgress on execution , binds tripID, updates size, and calculates nextTrip
void onNextClick ()
executes nextTrip();
void onPrevClick ()
executes prevTrip();
Public Member Functions
tripprogress (QWidget *parent=nullptr)
default explicit Constructor
~tripprogress ()
Destructor.
void displaySouv ()
updates sql query to update requested college souverniers and displays Ui table with updated model
void nextTrip ()
calculates and displays next destination for student planned trip
void prevTrip ()
calculates and displays previous destination for student planned trip
void getDistance ()
void updateCart ()
calculates and displays updated student cart for souveniers, total and quantity requested by the student at each school destination
void updateTotal ()
calculates and displays updated student price total for shopping souverniers from cart
Public Attributes
QString tripID
field member for storing tripID
QString currentCol
field member for storing currentCol(db)
QString souvenirName
field member for storing college souvenirName
double souvenirPrice
field member for storing college souvenirPrice
int row
field member for storing sql table row
Private Slots
void on_souvTable_clicked (const QModelIndex &index)
void on_addCart_clicked ()
updates database, cart, and total;
void on_pushButton_4_released ()
void on_removeCart_clicked ()
void on_pushButton_clicked ()
void on_pushButton_4_clicked ()
Private Attributes
Ui::tripprogress * ui
points to tripprogress UI
DbManager myDb = DbManager(PROJECT_PATH + "/college.db")
assigns DB to predefined PROJECT_PATH constant
QStringList trip
stores list of each trip/destination data
int counter
int max
Detailed Description
class for displaying and calculating student trip progress, destinations, and student shopping cart for souverniers
tripprogress displays an overview of what the user has planned for his trip this updates all data from souvenier, collegename, price, quantity, etc for the plan tripped, as well as the student cart, the student next, and previous destinations
Definition at line 28 of file tripprogress.h.
Constructor & Destructor Documentation
tripprogress()
tripprogress::tripprogress (QWidget * parent = nullptr) explicit
default explicit Constructor
Constructor sets up ui for tripprogress and initializes counter to default
Parameters
*parent - for QDialog
Definition at line 4 of file tripprogress.cpp.
References counter.
~tripprogress()
tripprogress::~tripprogress ()
Destructor.
Close the tripprogress UI
Definition at line 17 of file tripprogress.cpp.
References ui.
Member Function Documentation
displaySouv()
void tripprogress::displaySouv ()
updates sql query to update requested college souverniers and displays Ui table with updated model
Returns
nothing - void
Definition at line 200 of file tripprogress.cpp.
getDistance()
void tripprogress::getDistance ()
Definition at line 171 of file tripprogress.cpp.
Referenced by onLoadClick(), and onNextClick().
nextTrip()
void tripprogress::nextTrip ()
calculates and displays next destination for student planned trip
Returns
nothing - void
Definition at line 68 of file tripprogress.cpp.
References counter, confirmpage::getData(), max, confirmpage::on_okButton_released(), tripSummary::on_school_comboBox_currentIndexChanged(), updateCart(), and updateTotal().
Referenced by onLoadClick(), and onNextClick().
on_addCart_clicked
void tripprogress::on_addCart_clicked () private slot
updates database, cart, and total;
Returns
nothing - void
Definition at line 299 of file tripprogress.cpp.
References updateCart(), and updateTotal().
on_pushButton_4_clicked
void tripprogress::on_pushButton_4_clicked () private slot
on_pushButton_4_released
void tripprogress::on_pushButton_4_released () private slot
Definition at line 322 of file tripprogress.cpp.
References confirmpage::getData(), and confirmpage::on_okButton_released().
on_pushButton_clicked
void tripprogress::on_pushButton_clicked () private slot
on_removeCart_clicked
void tripprogress::on_removeCart_clicked () private slot
Definition at line 338 of file tripprogress.cpp.
References updateCart(), and updateTotal().
on_souvTable_clicked
void tripprogress::on_souvTable_clicked (const QModelIndex & index) private slot
Definition at line 280 of file tripprogress.cpp.
Referenced by tripPlanner::onStartClick().
onLoadClick
void tripprogress::onLoadClick () slot
initializes tripProgress on execution , binds tripID, updates size, and calculates nextTrip
Returns
nothing - void
Definition at line 24 of file tripprogress.cpp.
References getDistance(), and nextTrip().
onNextClick
void tripprogress::onNextClick () slot
executes nextTrip();
Returns
nothing - void
Definition at line 223 of file tripprogress.cpp.
References getDistance(), and nextTrip().
onPrevClick
void tripprogress::onPrevClick () slot
executes prevTrip();
Returns
nothing - void
Definition at line 229 of file tripprogress.cpp.
References prevTrip().
prevTrip()
void tripprogress::prevTrip ()
calculates and displays previous destination for student planned trip
Returns
nothing - void
Definition at line 133 of file tripprogress.cpp.
References counter.
Referenced by onPrevClick().
updateCart()
void tripprogress::updateCart ()
calculates and displays updated student cart for souveniers, total and quantity requested by the student at each school destination
Returns
nothing - void
Definition at line 234 of file tripprogress.cpp.
Referenced by nextTrip(), on_addCart_clicked(), and on_removeCart_clicked().
updateTotal()
void tripprogress::updateTotal ()
calculates and displays updated student price total for shopping souverniers from cart
Returns
nothing - void
Definition at line 255 of file tripprogress.cpp.
Referenced by nextTrip(), on_addCart_clicked(), and on_removeCart_clicked().
Member Data Documentation
counter
int tripprogress::counter private
Definition at line 159 of file tripprogress.h.
Referenced by nextTrip(), prevTrip(), and tripprogress().
currentCol
QString tripprogress::currentCol
field member for storing currentCol(db)
Definition at line 58 of file tripprogress.h.
max
int tripprogress::max private
Definition at line 160 of file tripprogress.h.
Referenced by nextTrip().
myDb
DbManager tripprogress::myDb = DbManager(PROJECT_PATH + "/college.db") private
assigns DB to predefined PROJECT_PATH constant
Definition at line 152 of file tripprogress.h.
row
int tripprogress::row
field member for storing sql table row
Definition at line 73 of file tripprogress.h.
souvenirName
QString tripprogress::souvenirName
field member for storing college souvenirName
Definition at line 63 of file tripprogress.h.
souvenirPrice
double tripprogress::souvenirPrice
field member for storing college souvenirPrice
Definition at line 68 of file tripprogress.h.
trip
QStringList tripprogress::trip private
stores list of each trip/destination data
Definition at line 157 of file tripprogress.h.
tripID
QString tripprogress::tripID
field member for storing tripID
Definition at line 53 of file tripprogress.h.
ui
Ui::tripprogress* tripprogress::ui private
points to tripprogress UI
Definition at line 147 of file tripprogress.h.
Referenced by ~tripprogress().
The documentation for this class was generated from the following files:
tripprogress.h
tripprogress.cpp