CS1D - Project1 - College Touring: addSouvenir Class Reference
addSouvenir Class Reference
#include <addsouvenir.h>
Public Member Functions
addSouvenir (QWidget *parent=nullptr)
explicit default Constructor
~addSouvenir ()
Destructor.
void updateCombo ()
Destructor.
Private Slots
void on_pushButton_2_released ()
void on_pushButton_released ()
executes process for adding a souvenir to database
Private Attributes
Ui::addSouvenir * ui
points to addSouvenir UI
DbManager myDb = DbManager(PROJECT_PATH + "/college.db")
assigns DB to predefined PROJECT_PATH constant
Detailed Description
Definition at line 12 of file addsouvenir.h.
Constructor & Destructor Documentation
addSouvenir()
addSouvenir::addSouvenir (QWidget * parent = nullptr) explicit
explicit default Constructor
Constructor intializes UI for addSouvenir calls updateCombo()
Parameters
*parent - for QDialog
Definition at line 4 of file addsouvenir.cpp.
References updateCombo().
~addSouvenir()
addSouvenir::~addSouvenir ()
Destructor.
Close the addSouvenir UI
Definition at line 13 of file addsouvenir.cpp.
References ui.
Member Function Documentation
on_pushButton_2_released
void addSouvenir::on_pushButton_2_released () private slot
Definition at line 40 of file addsouvenir.cpp.
Referenced by AdminWindow::on_addSouvenir_released().
on_pushButton_released
void addSouvenir::on_pushButton_released () private slot
executes process for adding a souvenir to database
Close the loginwindow UI
Definition at line 45 of file addsouvenir.cpp.
References confirmpage::getData(), and confirmpage::on_okButton_released().
updateCombo()
void addSouvenir::updateCombo ()
Destructor.
updates sql query for startcollege and sets ui Model
Definition at line 18 of file addsouvenir.cpp.
Referenced by addSouvenir().
Member Data Documentation
myDb
DbManager addSouvenir::myDb = DbManager(PROJECT_PATH + "/college.db") private
assigns DB to predefined PROJECT_PATH constant
Definition at line 60 of file addsouvenir.h.
ui
Ui::addSouvenir* addSouvenir::ui private
points to addSouvenir UI
Definition at line 55 of file addsouvenir.h.
Referenced by ~addSouvenir().
The documentation for this class was generated from the following files:
addsouvenir.h
addsouvenir.cpp