CS1D - Project2 - Baseball: AdminWindow Class Reference
AdminWindow Class Reference
class initializes AdminWindow UI and manages all Admin only permissive execution in editing user database, college database, souv database, etc
#include <adminwindow.h>
Public Member Functions
void updateCombo ()
AdminWindow (QWidget *parent=nullptr)
explicit default Constructor
void updateCollegeTable ()
updates sql data table for colleges when called
void updateSouvenirTable ()
updates sql data table for college souvenirs when called
~AdminWindow ()
Destructor.
Private Slots
void onInitialise ()
runs a verification of confirmPage, if verfied, initalizes distance, college, souvenir lists, updates appropiate data tables and UI models
void clearCollegeData ()
clears database of data
void on_addSouvenir_released ()
executes addSouvenir class obj
void on_removeSouvenir_released ()
deletes souvenir from data tables
void onAddColleges ()
adds college to connected database
void on_souvenirView_clicked (const QModelIndex &index)
displays and prints data from souvenir data set to UI
void on_removeSouvenir_2_clicked ()
void on_pushButton_5_released ()
void on_pushButton_2_clicked ()
void on_addMLB_clicked ()
void on_searchButton_clicked ()
void on_showALL_clicked ()
void on_showStadiums_clicked ()
void on_showStadiums_2_clicked ()
void on_pushButton_3_clicked ()
void on_pushButton_4_clicked ()
void on_pushButton_6_clicked ()
void souvTable ()
void on_pushButton_7_clicked ()
void on_souTable_clicked (const QModelIndex &index)
void on_pushButton_8_clicked ()
void on_updateButton_clicked ()
Private Attributes
QString souve
string stores temp souv data
Ui::AdminWindow * ui
points to adminwindow UI
DbManager myDb = DbManager(PROJECT_PATH + "/college.db")
assigns DB to predefined PROJECT_PATH constant
Detailed Description
class initializes AdminWindow UI and manages all Admin only permissive execution in editing user database, college database, souv database, etc
AdminWindow allows admin users only to intialize lists, edit lists, add individual college, souv data values
Definition at line 27 of file adminwindow.h.
Constructor & Destructor Documentation
AdminWindow()
AdminWindow::AdminWindow (QWidget * parent = nullptr) explicit
explicit default Constructor
Constructor intializes UI for adminwindow calls updateCollegeTable() and updateSouvenirTable()
Parameters
*parent - for QDialog
Definition at line 6 of file adminwindow.cpp.
References AdminWindow(), souvTable(), updateCollegeTable(), and updateSouvenirTable().
Referenced by AdminWindow().
~AdminWindow()
AdminWindow::~AdminWindow ()
Destructor.
Close the AdminWindow UI
Definition at line 17 of file adminwindow.cpp.
References ui.
Member Function Documentation
clearCollegeData
void AdminWindow::clearCollegeData () private slot
clears database of data
Returns
void - none
Definition at line 95 of file adminwindow.cpp.
References confirmpage::getData(), confirmpage::on_okButton_released(), updateCollegeTable(), and updateSouvenirTable().
on_addMLB_clicked
void AdminWindow::on_addMLB_clicked () private slot
Definition at line 181 of file adminwindow.cpp.
References confirmpage::getData(), confirmpage::on_okButton_released(), updateCollegeTable(), and updateSouvenirTable().
on_addSouvenir_released
void AdminWindow::on_addSouvenir_released () private slot
executes addSouvenir class obj
Returns
void - none
Definition at line 118 of file adminwindow.cpp.
References addSouvenir::on_pushButton_2_released(), and updateSouvenirTable().
on_pushButton_2_clicked
void AdminWindow::on_pushButton_2_clicked () private slot
Definition at line 176 of file adminwindow.cpp.
on_pushButton_3_clicked
void AdminWindow::on_pushButton_3_clicked () private slot
Definition at line 311 of file adminwindow.cpp.
on_pushButton_4_clicked
void AdminWindow::on_pushButton_4_clicked () private slot
Definition at line 336 of file adminwindow.cpp.
on_pushButton_5_released
void AdminWindow::on_pushButton_5_released () private slot
Definition at line 167 of file adminwindow.cpp.
on_pushButton_6_clicked
void AdminWindow::on_pushButton_6_clicked () private slot
Definition at line 361 of file adminwindow.cpp.
on_pushButton_7_clicked
void AdminWindow::on_pushButton_7_clicked () private slot
Definition at line 407 of file adminwindow.cpp.
References addSouvenir::on_pushButton_2_released(), and souvTable().
on_pushButton_8_clicked
void AdminWindow::on_pushButton_8_clicked () private slot
Definition at line 443 of file adminwindow.cpp.
References confirmpage::getData(), confirmpage::on_okButton_released(), and souvTable().
on_removeSouvenir_2_clicked
void AdminWindow::on_removeSouvenir_2_clicked () private slot
Definition at line 162 of file adminwindow.cpp.
on_removeSouvenir_released
void AdminWindow::on_removeSouvenir_released () private slot
deletes souvenir from data tables
Returns
void - none
Definition at line 128 of file adminwindow.cpp.
on_searchButton_clicked
void AdminWindow::on_searchButton_clicked () private slot
Definition at line 224 of file adminwindow.cpp.
on_showALL_clicked
void AdminWindow::on_showALL_clicked () private slot
Definition at line 250 of file adminwindow.cpp.
on_showStadiums_2_clicked
void AdminWindow::on_showStadiums_2_clicked () private slot
Definition at line 291 of file adminwindow.cpp.
on_showStadiums_clicked
void AdminWindow::on_showStadiums_clicked () private slot
Definition at line 271 of file adminwindow.cpp.
on_souTable_clicked
void AdminWindow::on_souTable_clicked (const QModelIndex & index) private slot
Definition at line 417 of file adminwindow.cpp.
on_souvenirView_clicked
void AdminWindow::on_souvenirView_clicked (const QModelIndex & index) private slot
displays and prints data from souvenir data set to UI
Returns
void - none
Definition at line 156 of file adminwindow.cpp.
on_updateButton_clicked
void AdminWindow::on_updateButton_clicked () private slot
Definition at line 491 of file adminwindow.cpp.
References confirmpage::getData(), confirmpage::on_okButton_released(), and souvTable().
onAddColleges
void AdminWindow::onAddColleges () private slot
adds college to connected database
Returns
void - none
Definition at line 133 of file adminwindow.cpp.
References confirmpage::getData(), confirmpage::on_okButton_released(), updateCollegeTable(), and updateSouvenirTable().
onInitialise
void AdminWindow::onInitialise () private slot
runs a verification of confirmPage, if verfied, initalizes distance, college, souvenir lists, updates appropiate data tables and UI models
Returns
void - none
Definition at line 62 of file adminwindow.cpp.
References confirmpage::getData(), confirmpage::on_okButton_released(), updateCollegeTable(), and updateSouvenirTable().
souvTable
void AdminWindow::souvTable () private slot
Definition at line 385 of file adminwindow.cpp.
Referenced by AdminWindow(), on_pushButton_7_clicked(), on_pushButton_8_clicked(), and on_updateButton_clicked().
updateCollegeTable()
void AdminWindow::updateCollegeTable ()
updates sql data table for colleges when called
Returns
void - none
Definition at line 22 of file adminwindow.cpp.
Referenced by AdminWindow(), clearCollegeData(), on_addMLB_clicked(), onAddColleges(), and onInitialise().
updateCombo()
void AdminWindow::updateCombo ()
Definition at line 204 of file adminwindow.cpp.
updateSouvenirTable()
void AdminWindow::updateSouvenirTable ()
updates sql data table for college souvenirs when called
Returns
void - none
Definition at line 41 of file adminwindow.cpp.
Referenced by AdminWindow(), clearCollegeData(), on_addMLB_clicked(), on_addSouvenir_released(), onAddColleges(), and onInitialise().
Member Data Documentation
myDb
DbManager AdminWindow::myDb = DbManager(PROJECT_PATH + "/college.db") private
assigns DB to predefined PROJECT_PATH constant
Definition at line 144 of file adminwindow.h.
souve
QString AdminWindow::souve private
string stores temp souv data
Definition at line 134 of file adminwindow.h.
ui
Ui::AdminWindow* AdminWindow::ui private
points to adminwindow UI
Definition at line 139 of file adminwindow.h.
Referenced by ~AdminWindow().
The documentation for this class was generated from the following files:
adminwindow.h
adminwindow.cpp